<?php

namespace NetFlex\LocationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	public function findCitiesInACountryAndStateByName($countryName, $stateName, $cityHint)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		return $qb->select('partial CT.{id, name}')
			->from('NetFlexLocationBundle:City', 'CT')
			->innerJoin('CT.stateId', 'S')
			->innerJoin('CT.countryId', 'C')
			->where($qb->expr()->andX(
				$qb->expr()->eq('C.name', ':countryName'),
				$qb->expr()->eq('S.name', ':stateName'),
				$qb->expr()->like('CT.name', $qb->expr()->literal("%$cityHint%")),
				$qb->expr()->eq('CT.status', 1)
			))
			->setParameters(['countryName' => $countryName, 'stateName' => $stateName])
			->getQuery()
			->getResult();
	}
}
