<?php

namespace NetFlex\LocationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
	public function findCountriesByName($countryName)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		return $qb->select('partial C.{id, name}')
			->from('NetFlexLocationBundle:Country', 'C')
			->where($qb->expr()->andX(
				$qb->expr()->like('C.name', $qb->expr()->literal("%$countryName%")),
				$qb->expr()->eq('C.status', 1)
			))
			->getQuery()
			->getResult();
	}
}
