net_flex_media:
    resource: "@NetFlexMediaBundle/Controller/"
    type:     annotation
    prefix:   /

net_flex_dashboard:
    resource: "@NetFlexDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
