services:
#    net_flex_user.example:
#        class: NetFlex\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.address:
        class: NetFlex\UserBundle\Form\AddressType
        arguments: ["@request_stack"]
        tags:
            - { name: form.type }
