services:
#    net_flex_user.example:
#        class: NetFlex\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.address:
        class: NetFlex\UserBundle\Form\AddressType
        arguments: ["@request_stack", "@doctrine.orm.default_entity_manager"]
        tags:
            - { name: form.type }

    app.form.email:
        class: NetFlex\UserBundle\Form\EmailType
        arguments: ["@request_stack"]
        tags:
            - { name: form.type }

    app.form.contact:
        class: NetFlex\UserBundle\Form\ContactType
        arguments: ["@request_stack"]
        tags:
            - { name: form.type }
