<?php

namespace NetFlex\MediaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
	/**
	 * Counts media records.
	 *
	 * @param string       $sortColumn
	 * @param string       $sortOrder
	 * @param string       $mediaName
	 * @param string       $mediaExtension
	 *
	 * @return int
	 */
	public function countMedias($sortColumn, $sortOrder, $mediaName = '', $mediaExtension = '')
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		$qb->select($qb->expr()->count('M.id') . ' media_count')->from('NetFlexMediaBundle:Media', 'M');
		
		if (! empty($mediaName)) {
			$qb->where($qb->expr()->like('M.mediaName', $qb->expr()->literal("%$mediaName%")));
		}
		
		if (! empty($mediaExtension)) {
			$qb->andWhere($qb->expr()->eq('M.mediaExtension', ':mediaExtension'))->setParameter('mediaExtension', $mediaExtension);
		}
		
		$qb->orderBy($sortColumn, $sortOrder);
		
		return $qb->getQuery()->getSingleResult()['media_count'];
	}
	
	/**
	 * Gets media records.
	 *
	 * @param int    $offset
	 * @param int    $limit
	 * @param string $sortColumn
	 * @param string $sortOrder
	 * @param string $mediaName
	 * @param string $mediaExtension
	 *
	 * @return array
	 */
	public function getMedias($offset, $limit, $sortColumn, $sortOrder, $mediaName, $mediaExtension)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		$qb->select('M')->from('NetFlexMediaBundle:Media', 'M');
		
		if (! empty($mediaName)) {
			$qb->where($qb->expr()->like('M.mediaName', $qb->expr()->literal("%$mediaName%")));
		}
		
		if (! empty($mediaExtension)) {
			$qb->andWhere($qb->expr()->eq('M.mediaExtension', ':mediaExtension'))->setParameter('mediaExtension', $mediaExtension);
		}
		
		$qb->orderBy($sortColumn, $sortOrder);
		
		$qb->setFirstResult($offset);
		$qb->setMaxResults($limit);
		
		return $qb->getQuery()->getResult();
	}
}
