<?php

namespace NetFlex\OrderBundle\Repository;

/**
 * ItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
