<?php

namespace NetFlex\OrderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemTypeRepository extends EntityRepository
{
	public function findActiveItemTypes()
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		return $qb->select('PT, ST')
			->from('NetFlexOrderBundle:ItemType', 'PT')
			->leftJoin(
				'PT.children',
				'ST',
				'WITH',
				$qb->expr()->eq('ST.status', 1)
			)
			->where($qb->expr()->isNull('PT.parentId'))
			->andWhere($qb->expr()->eq('PT.status', 1))
			->orderBy('PT.itemTypeName', 'ASC')
			->addOrderBy('ST.itemTypeName', 'ASC')
			->getQuery()
			->getResult();
	}
}
