<?php

namespace NetFlex\OrderBundle\Repository;

/**
 * OrderTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
