<?php

namespace NetFlex\StaticPageBundle\Repository;

/**
 * StaticPageSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticPageSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
