<?php

namespace NetFlex\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
	public function findClientPreferredAddresses($clientId)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		$qb->select('partial AT.{id, name}, partial A.{id, addressLine1, addressLine2, zipCode, isPrimary}, partial Co.{id, name}, partial S.{id, name}, partial Ci.{id, name}')
		->from('NetFlexUserBundle:Address', 'A')
		->leftJoin('A.addressTypeId', 'AT')
		->leftJoin('A.countryId', 'Co')
		->leftJoin('A.stateId', 'S')
		->leftJoin('A.cityId', 'Ci')
		->where($qb->expr()->andX(
			$qb->expr()->eq('A.userId', $clientId),
			$qb->expr()->eq('A.status', 1)
		))
		->orderBy('A.isPrimary', 'DESC')
		->addOrderBy('AT.id', 'ASC');
		
		$addresses = $qb->getQuery()->getResult();
		
		return $addresses;
	}
}
