<?php

namespace NetFlex\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
	public function findAnExistingUserEmail($email, $userId = null)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		$qb->select('partial E.{id, email}, partial U.{id}')
			->from('NetFlexUserBundle:Email', 'E')
			->innerJoin('E.userId', 'U')
			->where($qb->expr()->andX(
				$qb->expr()->eq('E.email', ':email'),
				$qb->expr()->eq('E.status', 1)
			));
		if ($userId) {
			$qb->andWhere($qb->expr()->neq('U.id', ':userId'));
			$qb->setParameter('userId', $userId);
		}
		$qb->setParameter('email', $email);
		$result = $qb->getQuery()->getResult();
		
		return ($result) ? count($result) : 0;
	}
	
	public function findClientPreferredOrFirstEmail($clientId)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		$result = $qb->select('E.email')
			->from('NetFlexUserBundle:Email', 'E')
			->where($qb->expr()->andX(
				$qb->expr()->eq('E.userId', ':clientId'),
				$qb->expr()->eq('E.status', 1)
			))
			->orderBy('E.isPrimary', 'DESC')
			->setFirstResult(0)
			->setMaxResults(1)
			->setParameters(['clientId' => $clientId])
			->getQuery()
			->getResult();
		
		return ($result) ? $result[0]['email'] : '';
	}
}
