<?php

namespace NetFlex\ShipmentTrackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderShipmentTrackRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderShipmentTrackRecordRepository extends EntityRepository
{
	public function findTrackRecordForAnOrder($orderId)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		$qb->select('partial O.{id, awbNumber}, partial TS.{id, name}, partial U1.{id, firstName, lastName}, partial U2.{id, firstName, lastName}, OSTR')
			->from('NetFlexShipmentTrackBundle:OrderShipmentTrackRecord', 'OSTR')
			->innerJoin('OSTR.orderId', 'O')
			->innerJoin('OSTR.trackStatusId', 'TS')
			->leftJoin('OSTR.createdBy', 'U1')
			->leftJoin('OSTR.lastModifiedBy', 'U2')
			->where($qb->expr()->eq('O.id', ':orderId'))
			->orderBy('TS.id', 'DESC')
			->setParameter('orderId', $orderId);
		
		$query = $qb->getQuery();
		
		return $query->getResult();
	}
}
