<?php

namespace NetFlex\ShipmentTrackBundle\Repository;

/**
 * TrackStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
