<?php

namespace NetFlex\DeliveryChargeBundle\Repository;

/**
 * DeliveryModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryModeRepository extends \Doctrine\ORM\EntityRepository
{
}
