<?php

namespace NetFlex\DeliveryChargeBundle\Repository;

/**
 * DeliveryChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
