<?php

namespace NetFlex\DeliveryChargeBundle\Repository;

/**
 * DeliveryModeTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryModeTimelineRepository extends \Doctrine\ORM\EntityRepository
{
}
