<?php

namespace NetFlex\DeliveryChargeBundle\Repository;

/**
 * DeliveryTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryTimelineRepository extends \Doctrine\ORM\EntityRepository
{
}
