<?php

namespace NetFlex\DeliveryChargeBundle\Repository;

/**
 * WeightUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeightUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
