<?php

namespace NetFlex\MailerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTemplateRepository extends EntityRepository
{
	public function findExistingEmailsForListing()
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		
		return $qb->select('MT.id, MT.typeKey, MT.typeName')
			->from('NetFlexMailerBundle:MailTemplate', 'MT')
			->orderBy('MT.id', 'DESC')
			->getQuery()
			->getResult();
	}
}
