services:
#    net_flex_delivery_charge.example:
#        class: NetFlex\DeliveryChargeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.type.check_deliverability:
        class: NetFlex\DeliveryChargeBundle\Form\CheckDeliverabilityType
        arguments: ['@doctrine.orm.default_entity_manager', '@request_stack']
        tags:
            - { name: form.type }
    app.form.type.delivery_charge_new:
        class: NetFlex\DeliveryChargeBundle\Form\DeliveryCharge\DeliveryChargeNewType
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: form.type }
    app.form.type.delivery_charge_edit:
        class: NetFlex\DeliveryChargeBundle\Form\DeliveryCharge\DeliveryChargeEditType
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: form.type }
